name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn ci --no-audit
    - run: yarn run lint --if-present
    - run: yarn test
    - run: yarn run build --if-present
      env:
        CI: true
